
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_loan
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    
      - "15672:15672" 

  web:
    build: .
    command: sh -c "python backend/manage.py migrate && python backend/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq

    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/web_loan
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: amqp://guest:guest@localhost:5672//

volumes:
  pgdata:
