# Generated by Django 5.1.7 on 2025-04-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pancard',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
