# Generated by Django 5.1.7 on 2025-04-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_aadhar_alter_user_pancard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='csv_file_url',
            field=models.FileField(blank=True, null=True, upload_to='transaction_csv/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
