# Generated by Django 5.1.7 on 2025-04-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_csv_file_url_alter_user_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_score',
            field=models.FloatField(null=True),
        ),
    ]
